### ISSUE TITLE
Any video tutorial?

### ISSUE THREAD

**Issue by YeeziesDax** [ExistedGit/Dota2Cheat#11]
WOuld really love it if someone would make a video tutorial for us non-coding peeps, im really bad at such things and would prefer if someone just drops a video (private) obviously not uploaded on public places, but maybe an unlisted youtube video, im asking too much iknow much sitll would love it ;-; <3 thanks

**Comment by ExistedGit** [comment]
I can do that. though I think you'd prefer me adding a release to this repo(so that you can download the DLL directly)

**Comment by 0xb4dc0d3x** [comment]
If you want, I can record tutorial video.

**Comment by ExistedGit** [comment]
It's just that I've been having a slight misunderstanding with Protobufs
I'll compile a statically linked release today so you won't need to put DLLs in the game's folder
Also need to resolve the issue with manual mapping since that would be the most secure injection method for internal

**Comment by Hoppedd** [comment]
ку,я инжекчу чит в доту через экстрим инжектор и мне пишет ошибку эту
![image](https://user-images.githubusercontent.com/76645020/221370201-04a34d91-67fb-469b-854b-90df1758cfdb.png)

**Comment by ExistedGit** [comment]
Скачай релиз из репозитория, там лежат 4 дллки, их надо закинуть в папку с
экзешником доты. Надо о них написать где-то, забыл совсем

**Comment by Hoppedd** [comment]
> Скачай релиз из репозитория, там лежат 4 дллки libprotobuf, их надо закинуть в папку с экзешником доты. Надо о них написать где-то, забыл совсем Хотя насколько я помню в папке с дллкой чита тоже билдится либпротобаф, закинь её если есть

![image](https://user-images.githubusercontent.com/76645020/221370468-e02ba285-011d-4af3-8390-0917ee96e061.png)
что именно я просто недавно начал разбирать твой сурс и тут обнова

**Comment by Hoppedd** [comment]
> Скачай релиз из репозитория, там лежат 4 дллки libprotobuf, их надо закинуть в папку с экзешником доты. Надо о них написать где-то, забыл совсем

перекинул я libprotobuf но крашит при инжекте появилась консолька с логами и инста краш

**Comment by Hoppedd** [comment]
а нет всё ворк сурс ахуенный люблю тебя дай дс хочу быть твоим учиником

**Comment by ExistedGit** [comment]
> а нет всё ворк , но крашит при заходе в лобби но всё же 
Я пока ещё тестирую, могу коммитать нерабочий код, пропуская или не замечая какие-то моменты

> дай дс хочу быть твоим учеником
Из меня плохой учитель, но если реально есть желание понять процесс и базовые компетенции в читах, то можно
DarkL1ght#1409
