### ISSUE TITLE
Crash on inject

### ISSUE THREAD

**Issue by Yolkie** [ExistedGit/Dota2Cheat#110]
I upgraded my OS to win 11 2h22 perfectly build the cheat with the help of one of the closed issue here however upon trying to inject my game closed after running the loader and this is the error below.

![image](https://user-images.githubusercontent.com/22864098/235343987-36108c37-697b-4173-bd9b-a2791b18f7a5.png)

**Comment by Yolkie** [comment]
^ tried the debug build it works however the overlay wont stay on top of the game.

**Comment by ExistedGit** [comment]
> ^ tried the debug build it works however the overlay wont stay on top of the game.

Seems like mapping is still unstable, while loadlibrary works? Either way, with a VAC bypass it won't spot you. My (supposedly) win10 assistant also reported that the mapper doesn't work. Might have to rewrite the thing.

Try to use some other injector(Extreme Injector, Xenos) with manual mapping

If you need fullscreen in debug, in dllmain.cpp find glfwWindowHint(GLFW_FLOATING, 1), move it out of the ifdef and rebuild

**Comment by Yolkie** [comment]
The dll provides the vac bypass or I should find one?

**Comment by ExistedGit** [comment]
> The dll provides the vac bypass or I should find one?

Read the README of the repo, it has two links(of which I prefer the VAC Inhibitor for its C++ modernity)
