### ISSUE TITLE
Clarification on a feature

### ISSUE THREAD

**Issue by huskyvvannafly** [ExistedGit/Dota2Cheat#137]
What is the use of pudgedumper and how can i use it? does it work together with dt2 dll(s)?

**Comment by ExistedGit** [comment]
PudgeDumper is a tool to update Dota2Cheats's netvar offsets. It also dumps the whole Schema to Documents/PudgeDumper.

(didn't call it Dota2Dumper not to plagiarise Liberalist's dumper with the same name)
