### ISSUE TITLE
The cheat crashes after update

### ISSUE THREAD

**Issue by Robff** [ExistedGit/Dota2Cheat#138]
Dota 2 updated recently 2-3 times so the cheat is instantly crashing ive tried so many things to disable some features that might crash it and tried to rebuild it nothing works you should look into it and update everything and repost when you can ive had 2 people try it aswell they have the same issue. Xenos doesn't seem to be working at all with it tried other injectors nothing the game works fine for like 5 minutes then when stuff happens like alot of abilities fly around it freezes and closes. Ive disabled everything off the only thing i have is True sight and ( hit the real clone)

**Comment by ExistedGit** [comment]
First of all, dota didn't have cheat-breaking updates since 7.33
Second of all, it may be related to Release generally not working because of the faulty cloud signature mechanism. Try again when I pull from testing
Third of all, I've been playing with bots for 12 minutes on that upcoming version and it's been perfectly fine

**Comment by Robff** [comment]
weird because everytime we inject with Xenos 64 bit it works completely fine for a moment in-game then crashes and sometimes when i try to inject it just crashes instantly wont even proceed anymore into the game. Removed downloaded the current version so many times and it keeps on crashing all the time can't seem to figure out whats causing it Is it something to do with the video settings like resolution? I doubt tho or maybe some other overlays interfere with it?

**Comment by ExistedGit** [comment]
> weird because everytime we inject with Xenos 64 bit it works completely fine for a moment in-game then crashes and sometimes when i try to inject it just crashes instantly wont even proceed anymore into the game. Removed downloaded the current version so many times and it keeps on crashing all the time can't seem to figure out whats causing it Is it something to do with the video settings like resolution? I doubt tho or maybe some other overlays interfere with it?

Try to debug it according to [the guide](https://github.com/ExistedGit/Dota2Cheat/blob/main/README.md#debugging) and see if it shows what kind of error it is

**Comment by someuser32** [comment]
> > weird because everytime we inject with Xenos 64 bit it works completely fine for a moment in-game then crashes and sometimes when i try to inject it just crashes instantly wont even proceed anymore into the game. Removed downloaded the current version so many times and it keeps on crashing all the time can't seem to figure out whats causing it Is it something to do with the video settings like resolution? I doubt tho or maybe some other overlays interfere with it?
> 
> Try to debug it according to [the guide](https://github.com/ExistedGit/Dota2Cheat/blob/main/README.md#debugging) and see if it shows what kind of error it is

![image](https://github.com/ExistedGit/Dota2Cheat/assets/102308925/1c6ebbbc-54a6-4a13-9b05-d2f08886f24a)

**Comment by ExistedGit** [comment]
Damn, it's that bad…

I honestly don't know what can break D2C that much. Is there a `signatures.json` file with data in `Documents\Dota2Cheat\`? I presume you have built & launched Dota2Loader at least once
