### ISSUE TITLE
Bars and AbilityESP not working

### ISSUE THREAD

**Issue by fasdblade** [ExistedGit/Dota2Cheat#150]
Bar and AbilityESP not working for me
Also all enemies are detected like illusions and they are red and illusions are red too
Here is a screenshot
![Untitled](https://github.com/ExistedGit/Dota2Cheat/assets/136919361/2e57a99f-4c57-4564-b660-644189437be1)

I tried to switch directx to vulkan and it's the same.
Tried to upgrade my Nvidia Drivers to latest version and tried to change Open GDI compatibility https://github.com/ExistedGit/Dota2Cheat/issues/5#issuecomment-1528731147
Also tried Verify integrity of game files and completely deleting Dota2 and then installing it again

I think I have all Visual C++ Redistributable 
![microsoft](https://github.com/ExistedGit/Dota2Cheat/assets/136919361/bc68dac8-68de-474d-8ef6-2d1a38211f71)

Any ideas how to fix this ?

Offtop:
And what is the key for mana abuse?

Thanks

**Comment by ExistedGit** [comment]
> Key for mana abuse

I currently don't possess any proper keybind technology, so it's automatic for now

Your problems must already be fixed with the latest commits to main. It's not related to any graphics issues, due to offsets shifting it regards them as illusions and illusions don't have AbilityESP. I assume you're using the latest release that was before the patch?

**Comment by fasdblade** [comment]
> I assume you're using the latest release that was before the patch?

Lastest compiled version from https://github.com/ExistedGit/Dota2Cheat/releases 
Dota2Cheat 12.06.2023

**Comment by ExistedGit** [comment]
> Lastest compiled version from https://github.com/ExistedGit/Dota2Cheat/releases 
> Dota2Cheat 12.06.2023

And that one was before 7.33d or c or what patch it is now. I think I'll make a new release(especially since now the Release version scans for far less signatures)

**Comment by fasdblade** [comment]
> I'll make a new release

Sorry for bothering you, but can you please make releases as soon as you merge changes to main? As I understand if a person wants to use latest version he needs to download sources and compile by himself. Downloading and installing Visual Studio and vcpkg takes time 
I tried to do so but I got error on installing vcpkg, sadly I found only one solution how to fix it and it didn't work. So for a regular Dota player it might cause difficulties and take time for download/install VS 
While for you as I understand it takes ~30seconds. 
So if you have free time I and other players will be very thankful

**Comment by ExistedGit** [comment]
> it takes ~30seconds

![Screenshot_1264](https://github.com/ExistedGit/Dota2Cheat/assets/66470490/d791b5c1-cac7-4a0a-81d4-6ac0241a0746)

What you perceive as a delay is me rebuilding functions for smaller initialization time. Basically, it's for your own good
