### ISSUE TITLE
Crash with inject new version cheat

### ISSUE THREAD

**Issue by KalitkaS** [ExistedGit/Dota2Cheat#192]
Crash after inject native or manual map. Only for new version

**Comment by KalitkaS** [comment]
![image](https://github.com/ExistedGit/Dota2Cheat/assets/69932434/180953e7-8f8d-44f3-8011-6c3c844eccb5)

**Comment by Stamp1de** [comment]
+1 Similar problem. Tried different injectors, but it looks like it's a new signature. client.dll was updated today.

**Comment by Stamp1de** [comment]
![2023_08_27_13_08_mvGY2hnTtD](https://github.com/ExistedGit/Dota2Cheat/assets/9316446/fcf04432-5388-40ae-8255-bf1ccbbbe742)
![devenv_2023_08_27_13_08_KqpDhMGRrP](https://github.com/ExistedGit/Dota2Cheat/assets/9316446/544e5580-017a-4e8b-b211-b1cc6f1f38c2)

**Comment by NaulbiMIX** [comment]
Use the [old injector published in the release](https://github.com/ExistedGit/Dota2Cheat/releases/download/v0.1/Dota2Cheat.zip), it works fine.

https://i.imgur.com/ExUUhAq.png

**Comment by KalitkaS** [comment]
> Use the [old injector published in the release](https://github.com/ExistedGit/Dota2Cheat/releases/download/v0.1/Dota2Cheat.zip), it works fine.
> 
> https://i.imgur.com/ExUUhAq.png

the old injector in the old archive to inject the old cheat, with the new version of the dll it does NOT work. I'm not stupid enough not to test it, and you made a mistake, you're using an old cheat and there's no business in the injector, the problem is in the file and working in the current version of dota.

**Comment by NaulbiMIX** [comment]
> > Use the [old injector published in the release](https://github.com/ExistedGit/Dota2Cheat/releases/download/v0.1/Dota2Cheat.zip), it works fine.
> > https://i.imgur.com/ExUUhAq.png
> 
> the old injector in the old archive to inject the old cheat, with the new version of the dll it does NOT work. I'm not stupid enough not to test it, and you made a mistake, you're using an old cheat and there's no business in the injector, the problem is in the file and working in the current version of dota.

If I used the old version of the cheat, it wouldn't work without the new signatures. The screenshot already has a new software menu, and the link to the release is old. Please try with the old injector and check if it works.

In addition, I specially cloned the repository and included debug for logs in it. Logs: https://pastebin.com/raw/CTxMzsZ7

**Comment by KalitkaS** [comment]
> > > Use the [old injector published in the release](https://github.com/ExistedGit/Dota2Cheat/releases/download/v0.1/Dota2Cheat.zip), it works fine.
> > > https://i.imgur.com/ExUUhAq.png
> > 
> > 
> > the old injector in the old archive to inject the old cheat, with the new version of the dll it does NOT work. I'm not stupid enough not to test it, and you made a mistake, you're using an old cheat and there's no business in the injector, the problem is in the file and working in the current version of dota.
> 
> If I used the old version of the cheat, it wouldn't work without the new signatures. The screenshot already has a new software menu, and the link to the release is old. Please try with the old injector and check if it works.
> 
> In addition, I specially cloned the repository and included debug for logs in it. Logs: https://pastebin.com/raw/CTxMzsZ7

I tried and it doesn't work, crash.

**Comment by NaulbiMIX** [comment]
> I tried and it doesn't work, crash.

How sad, apparently 2H22 makes itself felt.

**Comment by Stamp1de** [comment]
![ProcessHacker_2023_08_27_22_12_ylqjXSo3tf](https://github.com/ExistedGit/Dota2Cheat/assets/9316446/0d73eda8-874b-4daa-aa23-f4a6f54899ff)
then dota2 crash

**Comment by Stamp1de** [comment]
И что значит libprotobuf DLLs  ??

**Comment by NaulbiMIX** [comment]
> ![ProcessHacker_2023_08_27_22_12_ylqjXSo3tf](https://user-images.githubusercontent.com/9316446/263549274-0d73eda8-874b-4daa-aa23-f4a6f54899ff.png) then dota2 crash

Have you personally built the latest version of the software?

**Comment by NaulbiMIX** [comment]
> And what do you mean libprotobuf DLLs ??

https://github.com/ExistedGit/Dota2Cheat#building
https://github.com/microsoft/vcpkg

**Comment by Stamp1de** [comment]
> > ![ProcessHacker_2023_08_27_22_12_ylqjXSo3tf](https://user-images.githubusercontent.com/9316446/263549274-0d73eda8-874b-4daa-aa23-f4a6f54899ff.png)потом дота2 вылетает
> 
> Вы лично создали последнюю версию программного обеспечения?

Нет, я только разбираюсь как это должно работать

**Comment by NaulbiMIX** [comment]
> > > ![ProcessHacker_2023_08_27_22_12_ylqjXSo3tf](https://user-images.githubusercontent.com/9316446/263549274-0d73eda8-874b-4daa-aa23-f4a6f54899ff.png)потом дота2 вылетает
> > 
> > 
> > Вы лично создали последнюю версию программного обеспечения?
> 
> No, I'm just figuring out how it's supposed to work

So once again, are you using a version from releases or have you cloned the repository and built it yourself?

**Comment by Stamp1de** [comment]
> > > > ![ProcessHacker_2023_08_27_22_12_ylqjXSo3tf](https://user-images.githubusercontent.com/9316446/263549274-0d73eda8-874b-4daa-aa23-f4a6f54899ff.png)потом дота2 вылетает
> > > 
> > > 
> > > Вы лично представляете полную версию программного обеспечения?
> > 
> > 
> > Нет, я просто понимаю, как это должно работать
> 
> Итак, еще раз: вы используете версию из релизов или клонировали репозиторий и собрали его самостоятельно?

Now I just took what you suggested above from the releases. Didn't build it myself.

**Comment by NaulbiMIX** [comment]
> > > > > ![ProcessHacker_2023_08_27_22_12_ylqjXSo3tf](https://user-images.githubusercontent.com/9316446/263549274-0d73eda8-874b-4daa-aa23-f4a6f54899ff.png)потом дота2 вылетает
> > > > 
> > > > 
> > > > Вы лично представляете полную версию программного обеспечения?
> > > 
> > > 
> > > Нет, я просто понимаю, как это должно работать
> > 
> > 
> > Итак, еще раз: вы используете версию из релизов или клонировали репозиторий и собрали его самостоятельно?
> 
> Now I just took what you suggested above from the releases. Didn't build it myself.

Take the old injector, but compile the current version of the cheat. I personally compile a cheat with old protobuf since I don't want to update them. At the same time, I do not upgrade to 22H2, but sit on 21H2.

Try to take new and old protobuf, compile a cheat with them, and take the old injector.

**Comment by KalitkaS** [comment]
> 

well, you frankly write nonsense, no injector can bring this dll into the dota, because they conflict after micro-updating, perhaps.
I used both third-party and developer tools. I don't think 10 windows 22h2 matters.

**Comment by Stamp1de** [comment]
> > > > > > ![ProcessHacker_2023_08_27_22_12_ylqjXSo3tf](https://user-images.githubusercontent.com/9316446/263549274-0d73eda8-874b-4daa-aa23-f4a6f54899ff.png)потом дота2 вылетает
> > > > > 
> > > > > 
> > > > > Вы лично представляете полную версию программного обеспечения?
> > > > 
> > > > 
> > > > Нет, я просто понимаю, как это должно работать
> > > 
> > > 
> > > Итак, еще раз: вы используете версию из релизов или клонировали репозиторий и собрали его самостоятельно?
> > 
> > 
> > Now I just took what you suggested above from the releases. Didn't build it myself.
> 
> Take the old injector, but compile the current version of the cheat. I personally compile a cheat with old protobuf since I don't want to update them. At the same time, I do not upgrade to 22H2, but sit on 21H2.
> 
> Try to take new and old protobuf, compile a cheat with them, and take the old injector.

**Comment by Stamp1de** [comment]
> > > > > > ![ProcessHacker_2023_08_27_22_12_ylqjXSo3tf](https://user-images.githubusercontent.com/9316446/263549274-0d73eda8-874b-4daa-aa23-f4a6f54899ff.png)потом дота2 вылетает
> > > > > 
> > > > > 
> > > > > Вы лично представляете полную версию программного обеспечения?
> > > > 
> > > > 
> > > > Нет, я просто понимаю, как это должно работать
> > > 
> > > 
> > > Итак, еще раз: вы используете версию из релизов или клонировали репозиторий и собрали его самостоятельно?
> > 
> > 
> > Now I just took what you suggested above from the releases. Didn't build it myself.
> 
> Take the old injector, but compile the current version of the cheat. I personally compile a cheat with old protobuf since I don't want to update them. At the same time, I do not upgrade to 22H2, but sit on 21H2.
> 
> Try to take new and old protobuf, compile a cheat with them, and take the old injector.

![devenv_2023_08_27_23_26_6Si1BisfSU](https://github.com/ExistedGit/Dota2Cheat/assets/9316446/035d208e-8c5f-48b7-8ddb-d5133038bb09)

i am using vs22 and 21h2 but cant get build

**Comment by Stamp1de** [comment]
> > And what do you mean libprotobuf DLLs ??
> 
> https://github.com/ExistedGit/Dota2Cheat#building https://github.com/microsoft/vcpkg

I'm sorry I didn't notice this answer earlier.

**Comment by NaulbiMIX** [comment]
> > 
> 
> 
> 
> well, you frankly write nonsense, no injector can bring this dll into the dota, because they conflict after micro-updating, perhaps.
> 
> I used both third-party and developer tools. I don't think 10 windows 22h2 matters.

Funny. ☺️

**Comment by 2291109502** [comment]
> > > libprotobuf DLL 是什么意思？
> > 
> > 
> > [https://github.com/ExistedGit/Dota2Cheat#building ](https://github.com/ExistedGit/Dota2Cheat#building) https://github.com/microsoft/vcpkg
> 
> 很抱歉我之前没有注意到这个答案。 感谢您所做的这项出色的工作。超级酷！ ![dota2_2023_08_28_00_08_k6FngMvNRS](https://user-images.githubusercontent.com/9316446/263554023-b70b6896-92bc-4c1a-8604-1a8371cc4881.png)

could u please tell me what your vcpkg's version is?
i have tried so many version but crashed.

**Comment by NaulbiMIX** [comment]
> > > > libprotobuf DLL 是什么意思？
> > > 
> > > 
> > > [https://github.com/ExistedGit/Dota2Cheat#building ](https://github.com/ExistedGit/Dota2Cheat#building) https://github.com/microsoft/vcpkg
> > 
> > 
> > 很抱歉我之前没有注意到这个答案。 感谢您所做的这项出色的工作。超级酷！ ![dota2_2023_08_28_00_08_k6FngMvNRS](https://user-images.githubusercontent.com/9316446/263554023-b70b6896-92bc-4c1a-8604-1a8371cc4881.png)
> 
> could u please tell me what your vcpkg's version is? i have tried so many version but crashed.

https://github.com/microsoft/vcpkg/releases/tag/2023.04.15

**Comment by ExistedGit** [comment]
You guys are fighting a god damn war right there+ I personally always thought it can't possibly memorymap without crashes on someone else's PC. And iirc it even started to crash for me as well. Can't have nice things with protobufs, and the joke is that I can't even try and build them as separate DLLs, it just spews linker errors at me as if that was some other version

**Comment by Stamp1de** [comment]
> > > > libprotobuf DLL 是什么意思？
> > > 
> > > 
> > > [https://github.com/ExistedGit/Dota2Cheat#building ](https://github.com/ExistedGit/Dota2Cheat#building) https://github.com/microsoft/vcpkg
> > 
> > 
> > 很抱歉我之前没有注意到这个答案。 感谢您所做的这项出色的工作。超级酷！ ![dota2_2023_08_28_00_08_k6FngMvNRS](https://user-images.githubusercontent.com/9316446/263554023-b70b6896-92bc-4c1a-8604-1a8371cc4881.png)
> 
> could u please tell me what your vcpkg's version is? i have tried so many version but crashed.

I took the latest release available

**Comment by Stamp1de** [comment]
> You guys are fighting a god damn war right there! I personally always thought it can't possibly memorymap without crashes on someone else's PC. And iirc it even started to crash for me as well. Can't have nice things with protobufs, and the joke is that I can't even try and build them as separate DLLs(which works for Wolf49406's Crimson), it just spews linker errors at me as if that was some other version.

Wow... Wait, how did you solve this question for yourself then? o_o

Haha, if it works...

**Comment by ExistedGit** [comment]
> Wow... Wait, how did you solve this question for yourself then? o_o
> 
> Haha, if it works...

Must be a classical case of "works on my machine". People missing VC++ redistributables is also part of the problem, but who knew I needed to think of it months ago?

**Comment by Stamp1de** [comment]
> > Wow... Wait, how did you solve this question for yourself then? o_o
> > Haha, if it works...
> 
> Must be a classical case of "works on my machine". People missing VC++ redistributables is also part of the problem, but who knew I needed to think of it months ago?

 I don't think I have enough knowledge to help you develop this hack, but I'd be happy to help in general. I once tried to understand a little esange, hake.me, umbrella cheats.

**Comment by 2291109502** [comment]
https://imgur.com/a/YlUKkQ1
https://imgur.com/a/TJdWsB7
i could build dll , and launch Dota2Loader.exe successfully .
but finally crashed.   i dont know where the problem is .
could someone help me?

**Comment by zeon-unity** [comment]
> could build dll , and launch Dota2Loader.exe successfully .
> but finally crashed. i dont know where the problem is .
> could someone help me?

Maybe CMake will solve our problems?

**Comment by juzjus10** [comment]
it's broken right now

**Comment by zeon-unity** [comment]
I think we just need to update the sigs

**Comment by Stamp1de** [comment]
> I think we just need to update the sigs.
> 
> But I can't do without @ExistedGit , the thing is that I find xRefs but I get other signatures, it seems I'm highlighting the wrong expression to make sig.
> 
> If I succeeded, I would definitely send signatures here.

I looked at your git, 3 years ago you seem to have a good project

**Comment by juzjus10** [comment]
Yep sigs are outdated

**Comment by genchsusu** [comment]
In fact, all I need is TP display and illusion display. I just removed all other code and this seems works.

**Comment by ExistedGit** [comment]
> > Hey, can i get invite in ur private fork of that repository? ( i seen before, but u make it private and i cant message for u)
> 
> 
> The fact is that I deleted the fork and did not make it private.  I wanted to have nothing to do with DotA, freaked out))

Gigabased decision btw

**Comment by ExistedGit** [comment]
They broke everything, from D2Dumper to manabars. Now I'm not so sure about myself

**Comment by zeon-unity** [comment]
> They broke everything, from D2Dumper to manabars. Now I'm not so sure about myself

You can write down the problems you find, we can all try to help in any way we can

**Comment by KalitkaS** [comment]
there is no solution, the project is dead at the moment
