### ISSUE TITLE
Unable to click any thing after injecting

### ISSUE THREAD

**Issue by srinivasrk** [ExistedGit/Dota2Cheat#199]
Hello, love the efforts here and I did everything from scratch built and injected.

I can see the menu but cannot click in game anywhere.

![image](https://github.com/ExistedGit/Dota2Cheat/assets/11569731/3b6ddbd4-62e9-4875-bd72-d8a1d3253481)

I've tried all kinds of window mode and still have same issue.

Any suggesstions?

**Comment by JEJC** [comment]
Can you pls upload the release ?

**Comment by srinivasrk** [comment]
Not sure how to upload the .dll file here.

**Comment by L5DKAP** [comment]
Hi! Could you update file? 
![image](https://github.com/ExistedGit/Dota2Cheat/assets/68800926/7e358161-de66-4c95-90f8-ce359904e0df)

**Comment by JEJC** [comment]
Dota keep closing

**Comment by srinivasrk** [comment]
Using the ExtremInjector. @ExistedGit Can you help on this please?

**Comment by ep3264** [comment]
> Using the ExtremInjector. @ExistedGit Can you help on this please?

Which injection method did you use?  Because dota keep closing with ExtremInjector injector. Could you write configs? I'm going to test.
