### ISSUE TITLE
I have some problems with injecting 

### ISSUE THREAD

**Issue by kulzz** [ExistedGit/Dota2Cheat#2]
Yo. I builded this project and tried injecting dll with a shtreeba injector and nothing happened. I cant open interface with home or any buttons. Can I contact you anywhere?

**Comment by ExistedGit** [comment]
Shtreeba is for x32 while my project is x64(initally I tried shtreeba too)
Use extreme injector v3, I downloaded it from the unknowncheats forum
The console will appear immediately upon injecting and will show some
mostly debug information like pointers
