### ISSUE TITLE
inject

### ISSUE THREAD

**Issue by ishakq** [ExistedGit/Dota2Cheat#208]
how to inject a cheat and how to inject it???

**Comment by ishakq** [comment]
Mapping failed with error 0xc0000138. {Для продолжения нажмите любую клавишу . . . How to fix?

**Comment by ExistedGit** [comment]
Попробуй [релиз](https://github.com/ExistedGit/Dota2Cheat/releases/tag/7.37d), там есть инжектор\
Там проблема в том, что инжекторы не могут замаппить зависимость "C:\Windows\System32\d3dcompiler_43.dll" перед загрузкой Dota2Cheat.dll

**Comment by infikot** [comment]
> там есть инжектор
Как раз решил потестить всякие читы на дотку и.. Может я не совсем умный, а может у меня windows defender не выключен.. Запускаю инжектор от админа - доту крашит

**Comment by ishakq** [comment]
чет не работает,когда захожу в доту запускаю инжектор дота автоматом сворачивается,че делать??

**Comment by ishakq** [comment]
софт запустился,теперь другая проблема не могу закрыть окно доты плюс

**Comment by ishakq** [comment]
а,как софт загрузился,ниче сделать не могу

**Comment by ishakq** [comment]
все,дошло

**Comment by GloriousXX** [comment]
ты как то это решил?
