### ISSUE TITLE
Unable to inject

### ISSUE THREAD

**Issue by java17lzh** [ExistedGit/Dota2Cheat#30]
title

**Comment by 0xb4dc0d3x** [comment]
any logs or something?
- which injection method you use?
- any other information...

**Comment by ExistedGit** [comment]
Perfectly valid questions there ^
Does it crash or does nothing happen?
What injector are you using?
And most importantly what build are you injecting? I've left DX11 includes in the latest commit to main that I've used purely for testing. I don't think you'd go out of your way to get DX11 SDK for that

**Comment by java17lzh** [comment]
i us Dota2Loader .

The following information is listed:


works!
[INTERFACES]
Schema: 00007FFB4167A160
EntitySystem: 00000264D1A60000
CEngineClient: 00007FFB43EE4D00
Source2Client: 00007FFB33E91A10
CVarSystem: 00007FFB442F7150
Panorama: 00007FFB2B6B4718
Panorama2: 000002649FBC3800
GCClient: 00007FFB33F4E518
ParticleMgrSystem: 00007FFB38EC98C0
OnRemoveModifier: 00007FFB30A2D080
[GLOBAL POINTERS]
GameEventManagerPtr: 00007FFB33AD34B0
ProjectileManagerPtr: 00007FFB33E9EFB8
GameRulesPtr: 00007FFB33E932A8
PlayerResourcePtr: 00007FFB33E9EF28
DPMP: 00007FFB33AD36C0

**Comment by java17lzh** [comment]
![image](https://user-images.githubusercontent.com/44148913/224399499-6a1773e3-71ed-4c49-9584-7a6a7b1b8a96.png)
![image](https://user-images.githubusercontent.com/44148913/224399578-e7f3db66-108d-4f90-a546-e8d7757de04d.png)
![image](https://user-images.githubusercontent.com/44148913/224399643-ce42da6d-d050-4db2-b70f-7177c62254e8.png)

**Comment by ExistedGit** [comment]
So it DOES work
If it crashes when you enter the game, wait for a commit to main and rebuild
If it'll still crash somewhere else, build the project in Debug configuration, attach Visual Studio's debugger to dota2.exe(Ctrl + Alt + P) and inject. Then at least you'll be able to tell me where the error occurs
The only thing I know for sure is that it crashes when you exit a match

**Comment by java17lzh** [comment]
![image](https://user-images.githubusercontent.com/44148913/224403375-9facd034-499f-4afb-bd9b-92c6026bcf56.png)
this？

**Comment by java17lzh** [comment]
I don't know the code, so I can't provide you with more error information

**Comment by ExistedGit** [comment]
filesystem...
Sure as hell caused by the cheat trying to load Lua scripts from a nonexistent folder
Thanks for cooperating, pull from main and try to use it now
I'll update the loader later so it'd create these folders if they're missing

**Comment by java17lzh** [comment]
![image](https://user-images.githubusercontent.com/44148913/224406151-d9875895-c8e6-40e4-b7ac-8b47e8c6c60d.png)
ok, Is this set in the game？

**Comment by ExistedGit** [comment]
This cheat creates a separate transparent window on top of Dota
Should not depend on graphics settings

**Comment by java17lzh** [comment]
Are updated? I can't wait to try

**Comment by ExistedGit** [comment]
yes
shouldn't crash in-game but will crash when you quit(currently unable to tell why)

**Comment by java17lzh** [comment]
Thank you. It's ready to use

**Comment by java17lzh** [comment]
very powerful. Is it possible to realize automatic avoidance?

**Comment by ExistedGit** [comment]
If you mean AutoDodge, it has that for projectiles(dodges things like Sniper's ultimate with manta style or bottled illusion rune)

Other variants like evading Axe's first spell are yet to be implemented, and they wouldn't be as hard for me to do

Also I suppose there's a variant where it tries to dodge things like Meat Hook and that'd be harder to do but still possible
