### ISSUE TITLE
crash on inject

### ISSUE THREAD

**Issue by Fckrx** [ExistedGit/Dota2Cheat#41]
![image](https://user-images.githubusercontent.com/129055656/227910730-608d99d4-efa0-4538-8f41-cc078987b60e.png)

**Comment by ExistedGit** [comment]
It's very strange that PrepareUnitOrders signature wasn't found
I tested it numerous times with the current sig and it was fine

**Comment by abevol** [comment]
Using 4096 slice memory blocks is not a good idea when scanning signatures.

**Comment by ExistedGit** [comment]
> Using 4096 slice memory blocks is not a good idea when scanning signatures.

How should it be then? I haven't really looked into sigscanning after I added it in the beginning, seemed to work fine(mostly)

**Comment by abevol** [comment]
> > Using 4096 slice memory blocks is not a good idea when scanning signatures.
> 
> How should it be then? I haven't really looked into sigscanning after I added it in the beginning, seemed to work fine(mostly)

As you know, it sometimes splits the signature of the target memory into two parts, so we should use a continuous memory scan technique.

**Comment by ExistedGit** [comment]
> > > Using 4096 slice memory blocks is not a good idea when scanning signatures.
> > 
> > 
> > How should it be then? I haven't really looked into sigscanning after I added it in the beginning, seemed to work fine(mostly)
> 
> As you know, it sometimes splits the signature of the target memory into two parts, so we should use a continuous memory scan technique.

Well, sounds quite logical(I thought that too). And I think splitting it into parts doesn't make it better anyway

**Comment by Fckrx** [comment]
so, how i can fix this?

**Comment by Fckrx** [comment]
![image](https://user-images.githubusercontent.com/129055656/228139157-bcf95519-e46f-4f9d-acd8-e7fbb1db76c7.png)

**Comment by ExistedGit** [comment]
Could you build it in Debug and show me the Call stack of that exception?
I'm fairly sure on where it's crashing but I need more data

**Comment by Fckrx** [comment]
![image](https://user-images.githubusercontent.com/129055656/228308235-9809de08-2a0f-4080-bb1b-47b3a117637d.png)
Папки в документах нет
