### ISSUE TITLE
I can't compile loader

### ISSUE THREAD

**Issue by JasonFortis** [ExistedGit/Dota2Cheat#44]
In visual studio it says no files in folder but i'm 0 in programming so i dont know how to compile( can you help? Or can i use different injector?

**Comment by ExistedGit** [comment]
You can try manually moving the assets and scripts folder to Documents\Dota2Cheat and then inject with something else
The only thing the loader does apart from injection is moving all that stuff for you

**Comment by JasonFortis** [comment]
> 

Will new compiled version be released?

**Comment by ExistedGit** [comment]
> Will new compiled version be released?

If you show me what error Visual Studio displays, I might be able to fix it

**Comment by JasonFortis** [comment]
There is 27 errors all depends on files that are not in folder,
![image](https://user-images.githubusercontent.com/104436767/228223015-be42ba5f-5057-4008-aeaf-1d9a70e66bdc.png)

**Comment by JasonFortis** [comment]
Or if it's not difficult, you can record a video tutprial for compiling this for noobs like me

**Comment by ExistedGit** [comment]
Походу нужно реально сделать свой меморимаппер, как Вульф говорил

**Comment by dvrkinside** [comment]
У меня после фикса отлично все воркает
Только в катке опять даже отдаление не работает
Хотя, раньше не работали только ордера (писал issue с другого аккаунта)

**Comment by ExistedGit** [comment]
> У меня после фикса отлично все воркает Только в катке опять даже отдаление не работает Хотя, раньше не работали только ордера (писал issue с другого аккаунта)

С ботами на Стокгольме лично у меня нормально работает, не понимаю суть проблемы

**Comment by JasonFortis** [comment]
![image](https://user-images.githubusercontent.com/104436767/228343300-f0ea6f46-2bbf-4f85-b2b2-b393acaaf9c5.png)
Что бы я не делал cor.h всегда не найден
хотя он есть

**Comment by ExistedGit** [comment]
Можешь попробовать последний релиз, там уже всё скомпилено

**Comment by ExistedGit** [comment]
> У меня в релизе компилится лоадер, а в дебаге нет)

У меня на клонированной версии main компилируется

**Comment by F0RQU1N** [comment]
Я не перестаю пытаться использовать это в дебаге, теперь при заходе на мапу такое
![image](https://user-images.githubusercontent.com/108815933/228889211-dc0288bb-7aef-4797-ad78-9ca8b47ed3e5.png)

**Comment by ExistedGit** [comment]
А где эксепшн вылезает, если в VS дебажить?
Файлсистема опять шалит?

**Comment by F0RQU1N** [comment]
> А где эксепшн вылезает, если в VS дебажить? Файлсистема опять шалит?

ntdll

**Comment by ExistedGit** [comment]
> ntdll

А у меня самого так иногда, часто при реинджекшне. Хрен его знает, что это такое
