### ISSUE TITLE
Crashing when using Mango, Stick and etc..

### ISSUE THREAD

**Issue by Yolkie** [ExistedGit/Dota2Cheat#62]
In my investigation whenever it crashed and reconnected the items are dropped.

It is probably crashing because of the trick where you drop the items and use Mango, Arcane, Stick and etc, to gain more mana/health.

**Comment by ExistedGit** [comment]
Hmm, just now on my build I tested it(and I haven't changed the feature) and it's fine

Maybe eliminating the old EntityIteration helped, since it crashed when entities were  added/removed

I'll merge it into main soon so you can try

**Comment by Yolkie** [comment]
Compiled the merged source today still encountered the issue.

Disabled auto use farie/stick.
Nothing else changed.

Used mango > crashed > reconnected > items dropped before crashing (wards, branch).
