### ISSUE TITLE
Is it possible to add automatic armlet mode for Huskar like magic wand?

### ISSUE THREAD

**Issue by ExistedGit** [ExistedGit/Dota2Cheat#8]
Is it possible to add automatic armlet mode for Huskar like magic wand?

_Originally posted by @Aligg20 in https://github.com/ExistedGit/Dota2Cheat/issues/5#issuecomment-1424622117_

**Comment by ExistedGit** [comment]
yes, I'm refining the algorythm for it

**Comment by 0xb4dc0d3x** [comment]
This is awesome, automatic armlet abusing can be useful for many heroes. like lifestealer.

**Comment by ExistedGit** [comment]
> This is awesome, automatic armlet abusing can be useful for many heroes. like lifestealer.

But it'll take time too since I need to get all that attack animation and attack target stuff working

**Comment by Aligg20** [comment]
It's great, I can't wait for this update, thank you very much.

**Comment by ExistedGit** [comment]
Update on this one: I'll be adding a Lua API and before/after it I'll do this feature, I have all the needed tools for that

**Comment by ExistedGit** [comment]
Update on that one: I can't tell I didn't overestimate myself. But that doesn't mean the feature will not be implemented either
