### ISSUE TITLE
Dota 2 Game Coordinator

### ISSUE THREAD

**Issue by Yolkie** [ExistedGit/Dota2Cheat#81]
Whenever the cheat is injected (only in lobby)
![image](https://user-images.githubusercontent.com/22864098/232227365-7c06157a-aee7-4ffa-8d2a-5e14f47165db.png)

**Comment by ExistedGit** [comment]
Might be because of GC hooks

I'll disable them in the next PR to main(need to polish the TP tracker). They will be used in the skinchanger if/when time comes but currently they don't do anything

**Comment by ExistedGit** [comment]
Try to use it now

**Comment by Yolkie** [comment]
It is working pretty well now though the trackers sometimes is not accurate but not really a problem because of the show all particles
