### ISSUE TITLE
Possible to make dota plus item buyable?

### ISSUE THREAD

**Issue by hun2memory** [ExistedGit/Dota2Cheat#91]
For example when i try to buy any sound wheel:

`WARNING: Aborting ClaimEventAction for EventActionID: 43032, number of grants (0) exceeds maximum (0), user does not own event: EVENT_ID_PLUS_SUBSCRIPTION.`

**Comment by ExistedGit** [comment]
Well, as it says, you don't have a Dota Plus subscription

I probably wouldn't be able to unlock chat wheel phrases, the GC things are too hard to reverse

**Comment by hun2memory** [comment]
Well sad to hear i hope someone found it
Anyway do you have a plan to implement a 'true sight' esp? that simply indicate you when near a gem/sentry almost every hax i used has this feature

**Comment by ExistedGit** [comment]
> Well sad to hear i hope someone found it
> Anyway do you have a plan to implement a 'true sight' esp? that simply indicate you when near a gem/sentry almost every hax i used has this feature

I think I remember hearing about that one somewhere. I'll look into it

**Comment by hun2memory** [comment]
> I think I remember hearing about that one somewhere. I'll look into it

Forgot to mention  There is also a cool feature i used maybe like 1y ago on other hax
[Custom Chat Wheel](https://img001.prntscr.com/file/img001/XXmGyYfvQGGc9sqk24IslQ.jpg)
I hear it is work basically by passing a custom html into cmd wheel. I hope you found a way to do that and try to implement in the future.
Anyway i might talking too much and i dont wanna oot
if i have an issue or any implementation in the future i might just open the new topic then
Thankyou for your awesome project and your kindness sir @ExistedGit Have a good day!
